<a href="https://colab.research.google.com/github/siddhartha-sai-17/Deep-Learning/blob/main/CarPrice_Prediction_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving CarPrice_dataset.csv to CarPrice_dataset.csv

In [2]:
import pandas as pd
import io
df = pd.read_csv('CarPrice_dataset.csv')

In [3]:
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [4]:
df.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

X = df.drop(columns='price')
y = df['price']

# Identify categorical and numerical columns
categorical_cols = X.select_dtypes(include=['object']).columns.tolist()
numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()

# Define Preprocessing steps
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_cols),
        ('car', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
    ]
)

# Apply Preprocessing
X_processed = preprocessor.fit_transform(X)

# Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X_processed, y, test_size=0.2, random_state=42
)

In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Define the model
model = Sequential([
    Dense(512, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(256, activation='relu'),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1)
])

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 512)            │       102,912 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 277,505 (1.06 MB)

 Trainable params: 277,505 (1.06 MB)

 Non-trainable params: 0 (0.00 B)

In [9]:
history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 4s 254ms/step - loss: 217238208.0000 - val_loss: 317882208.0000
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 118ms/step - loss: 210801328.0000 - val_loss: 317681472.0000
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 99ms/step - loss: 184894128.0000 - val_loss: 317111904.0000
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 119ms/step - loss: 206500576.0000 - val_loss: 315632480.0000
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 182ms/step - loss: 224490320.0000 - val_loss: 312210816.0000
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 143ms/step - loss: 228352688.0000 - val_loss: 304574336.0000
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 185509296.0000 - val_loss: 288594400.0000
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 196037616.0000 - val_loss: 256762592.0000
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 111ms/step - loss: 157923904.0000 - val_loss: 200936192.0000
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 86ms/step - loss: 111679536.0000 - val_loss: 120964288.0000
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 61789264.0000 - val_loss: 40766368.0000
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 18356262.0000 - val_loss: 21305600.0000
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 25016128.0000 - val_loss: 16041710.0000
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 15583326.0000 - val_loss: 17531510.0000
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 11515756.0000 - val_loss: 22245000.0000
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 13097253.0000 - val_loss: 15649057.0000
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 11099391.0000 - val_loss: 11379453.0000
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 7957415.5000 - val_loss: 10705587.0000
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 8966382.0000 - val_loss: 10818099.0000
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 5539869.5000 - val_loss: 11246951.0000
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 7597462.0000 - val_loss: 11119645.0000
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 6029149.0000 - val_loss: 12664200.0000
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 6157890.0000 - val_loss: 12118549.0000
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5566778.0000 - val_loss: 10226614.0000
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 4626150.0000 - val_loss: 10121672.0000
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 4904335.5000 - val_loss: 10803356.0000
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 4138624.0000 - val_loss: 10730051.0000
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 4277828.0000 - val_loss: 10671222.0000
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 3296409.5000 - val_loss: 10238210.0000
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 3342635.2500 - val_loss: 9672914.0000
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 3473972.0000 - val_loss: 9454163.0000
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 3163274.5000 - val_loss: 9516236.0000
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 3040667.0000 - val_loss: 10881730.0000
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 3008425.2500 - val_loss: 10640535.0000
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 2638402.5000 - val_loss: 10053182.0000
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 2620609.0000 - val_loss: 11051196.0000
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 2222719.0000 - val_loss: 10217373.0000
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 2624500.5000 - val_loss: 9519406.0000
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2159875.5000 - val_loss: 10273368.0000
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 1918792.5000 - val_loss: 11192474.0000
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 2217543.5000 - val_loss: 10389196.0000
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 87ms/step - loss: 1654340.7500 - val_loss: 9281255.0000
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 69ms/step - loss: 1775965.3750 - val_loss: 9971388.0000
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - loss: 1798595.0000 - val_loss: 9662262.0000
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 119ms/step - loss: 1767657.3750 - val_loss: 9335830.0000
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 1554847.3750 - val_loss: 9302349.0000
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 1516941.2500 - val_loss: 9452143.0000
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 93ms/step - loss: 1580591.3750 - val_loss: 9401192.0000
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 1267344.0000 - val_loss: 9359796.0000
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 1491359.8750 - val_loss: 9499929.0000
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 1192174.6250 - val_loss: 9585600.0000
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 1110551.7500 - val_loss: 9491909.0000
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 1148435.3750 - val_loss: 9413666.0000
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 72ms/step - loss: 989489.1250 - val_loss: 9349878.0000
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 97ms/step - loss: 1237842.5000 - val_loss: 9234382.0000
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 1203471.3750 - val_loss: 9670786.0000
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 97ms/step - loss: 1007509.5000 - val_loss: 9625430.0000
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - loss: 1019597.1250 - val_loss: 9034967.0000
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 86ms/step - loss: 996790.1875 - val_loss: 9147899.0000
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 836385.2500 - val_loss: 9673780.0000
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 89ms/step - loss: 939926.6250 - val_loss: 10237921.0000
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - loss: 854337.2500 - val_loss: 9857257.0000
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 808932.0000 - val_loss: 9157012.0000
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 965819.0625 - val_loss: 9160450.0000
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 974111.6875 - val_loss: 9681470.0000
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 175ms/step - loss: 653414.3125 - val_loss: 9392735.0000
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 149ms/step - loss: 693385.6250 - val_loss: 8937796.0000
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 140ms/step - loss: 651392.3750 - val_loss: 9618305.0000
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 118ms/step - loss: 731606.6250 - val_loss: 9962682.0000
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 660606.7500 - val_loss: 9147117.0000
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - loss: 563159.5625 - val_loss: 8572678.0000
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 99ms/step - loss: 788881.1250 - val_loss: 8635859.0000
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 635353.6250 - val_loss: 9477626.0000
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 624461.1250 - val_loss: 9811044.0000
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 560327.0625 - val_loss: 8879459.0000
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 144ms/step - loss: 559932.5625 - val_loss: 8747749.0000
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 520639.1250 - val_loss: 9064386.0000
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 460686.2500 - val_loss: 9102677.0000
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 496059.7188 - val_loss: 9021742.0000
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 122ms/step - loss: 601921.5000 - val_loss: 9267232.0000
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 198ms/step - loss: 478439.5625 - val_loss: 9699072.0000
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 73ms/step - loss: 595889.0000 - val_loss: 9275342.0000
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 393722.6562 - val_loss: 8728062.0000
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - loss: 485039.7500 - val_loss: 8884640.0000
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 392469.3438 - val_loss: 9418679.0000
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 386686.8750 - val_loss: 9376525.0000
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 380948.6250 - val_loss: 9077707.0000
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 382838.5312 - val_loss: 9084095.0000
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 401081.6875 - val_loss: 9251653.0000
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 409433.5000 - val_loss: 9020912.0000
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 396783.3750 - val_loss: 8658490.0000
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 388072.1875 - val_loss: 8889537.0000
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 340373.5312 - val_loss: 9280904.0000
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 332954.2500 - val_loss: 9399096.0000
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 91ms/step - loss: 378727.6250 - val_loss: 9053549.0000
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 301679.4688 - val_loss: 9117410.0000
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 300556.6875 - val_loss: 9631857.0000
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 276463.0312 - val_loss: 9103620.0000
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 297728.1875 - val_loss: 8700920.0000
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 272318.4062 - val_loss: 8856552.0000

In [10]:
# Model Evaluation
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error: {mae}")
print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
Mean Absolute Error: 1799.5880809832317
Mean Squared Error: 7288145.8875680845
R-squared: 0.9076795708356667